"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""


def sum_even_fibonacci(maximum):
    # Start values
    start_1 = 1
    start_2 = 2

    # Current fibonacci value
    current = start_2
    previous = start_1

    # Variable to store result
    total = start_2

    # Loop through all the numbers below max
    while current <= maximum:
        # Store the current value
        tmp = current

        # Calculate the new fibonacci value
        current += previous

        # Update previous
        previous = tmp

        # If te value is even
        if current % 2 == 0:
            # Add that number to the total
            total += current

    # Print the result
    print total


if __name__ == '__main__':
    sum_even_fibonacci(4000000)
